using System;
using System.Collections.Generic;

namespace Database_Example_3.Models;

public partial class AnnouncementMatchingList
{
    public long AnnouncementMatchingListId { get; set; }

    public long AnnouncementId { get; set; }

    public DateTime CreateDate { get; set; }

    public long CreateUserId { get; set; }

    public bool IsAutoGenerated { get; set; }

    public long IsRegenerated { get; set; }

    public DateTime? LastUpdateDate { get; set; }

    public long? LastUpdateUserId { get; set; }

    public int ApprovalStatusId { get; set; }

    public DateTime? ApproveDate { get; set; }

    public long? ApproveUserId { get; set; }

    public DateTime? PlannedSendDate { get; set; }

    public bool IsEmailGenerated { get; set; }

    public long? EmailMessageId { get; set; }

    public int GenerationStatusId { get; set; }

    public DateTime? LastGenerationDate { get; set; }

    public bool IsPriority { get; set; }

    public bool IsCvAccessActive { get; set; }

    public int? CvAccessDays { get; set; }

    public DateTime? CvAccessExpireDate { get; set; }
}
