using System;
using System.Collections.Generic;

namespace Database_Example_3.Models;

public partial class Order
{
    public long OrderId { get; set; }

    public string? OrderNumber { get; set; }

    public long CustomerId { get; set; }

    public decimal Discount { get; set; }

    public decimal TotalPrice { get; set; }

    public DateTime CreateDate { get; set; }

    public long CreateUserId { get; set; }

    public int StatusId { get; set; }

    public int ShippingStatusId { get; set; }

    public string? ProFormaInvoiceFileId { get; set; }

    public bool? IsPartialShippingAllowed { get; set; }

    public bool IsAutoGenerated { get; set; }

    public long? OriginalOrderId { get; set; }

    public long? CancelUserId { get; set; }

    public DateTime? CancelDate { get; set; }

    public long? DeleteUserId { get; set; }

    public DateTime? DeleteDate { get; set; }

    public long? RejectUserId { get; set; }

    public DateTime? RejectDate { get; set; }

    public DateTime? PartialShippingDate { get; set; }

    public DateTime? ShippingDate { get; set; }

    public bool IsStandalone { get; set; }

    public bool IsOverriden { get; set; }

    public long? RootOrderId { get; set; }

    public long? OverrideOrderId { get; set; }
}
